### ISSUE TITLE
Improvement: Sound trigger Infinite Range flag

### ISSUE THREAD

**Issue by shaperones0** [TheEnderek0/Enderek-s_packages#3]
add property for sound trigger which adds Infinite Range flag, so it do not fade out when you walk further from trigger

**Comment by shaperones0** [comment]
or, i think, this would be a bit more logic to have this flag turned on by default, since, in my opinion, this trigger will be primarily used to play music, or voice, which do not fit very well with the fact that sound becomes drastically quieter as you step just a few voxels away

**Comment by shaperones0** [comment]
i've commented this since i've come through files of sound trigger, and, although im not really good in package-making for beemod, i thought that adding another property for flag (to existing "Is NOT Looped") will result in bulky 4 more files to add, differing with just a one line

**Comment by TheEnderek0** [comment]
Done
